// gateway/src/main/webapp/app/admin/gateway/gateway.vue
<template>
  <div>
    <h2>
      <span id="gateway-page-heading" v-text="t$('gateway.title')"></span>
      <button class="btn btn-primary float-right" @click="refresh()" :disabled="updatingRoutes">
        <font-awesome-icon icon="sync"></font-awesome-icon> <span v-text="t$('gateway.refresh.button')"></span>
      </button>
    </h2>
    <h3 v-text="t$('gateway.routes.title')"></h3>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th v-text="t$('gateway.routes.url')"></th>
            <th v-text="t$('gateway.routes.service')"></th>
            <th v-text="t$('gateway.routes.servers')"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="route of gatewayRoutes" :key="route.serviceId">
            <td>{{ route.path }}</td>
            <td>{{ route.serviceId }}</td>
            <td>
              <div v-if="route.serviceInstances.length === 0" class="label label-danger" v-text="t$('gateway.routes.error')"></div>
              <div class="table-responsive">
                <table class="table table-striped" v-if="route">
                  <tr v-for="instance of route.serviceInstances" :key="instance.uri">
                    <td>
                      <a :href="instance.uri" target="_blank">{{ instance.uri }}</a>
                    </td>
                    <td>
                      <div
                        v-if="instance.instanceInfo"
                        class="badge"
                        :class="'badge-' + (instance.instanceInfo.status === 'UP' ? 'success' : 'danger')"
                      >
                        {{ instance.instanceInfo.status }}
                      </div>
                      <div v-if="!instance.instanceInfo" class="badge badge-warning">?</div>
                    </td>
                    <td>
                      <span v-for="(entry, key) of instance.metadata" :key="key">
                        <span class="badge badge-default font-weight-normal">
                          <span class="badge badge-pill badge-info font-weight-normal">{{ key }}</span>
                          <span class="text-secondary">{{ entry }}</span>
                        </span>
                      </span>
                    </td>
                  </tr>
                </table>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script lang="ts" src="./gateway.component.ts"></script>

// gateway/src/main/webapp/app/modules/administration/gateway/gateway.tsx
import React, { useEffect } from 'react';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { Badge, Button, Table } from 'reactstrap';

import { useAppDispatch, useAppSelector } from 'app/config/store';
import { getGatewayRoutes } from '../administration.reducer';

export const GatewayPage = () => {
  const dispatch = useAppDispatch();
  const isFetching = useAppSelector(state => state.administration.loading);
  const routes = useAppSelector(state => state.administration.gateway.routes);

  useEffect(() => {
    dispatch(getGatewayRoutes());
  }, []);

  const metadata = instance => {
    const spans = [];
    Object.keys(instance).map((key, index) => {
      spans.push(
        <span key={`${key.toString()}value`}>
          <Badge key={`${key.toString()}-containerbadge`} className="fw-normal">
            <Badge key={`${key.toString()}-badge`} color="info" className="fw-normal" pill>
              {key}
            </Badge>
            {instance[key]}
          </Badge>
        </span>,
      );
    });
    return spans;
  };

  const badgeInfo = info => {
    if (info) {
      if (info.checks && info.checks.filter(check => check.status === 'PASSING').length === info.checks.length) {
        return <Badge color="success">UP</Badge>;
      }
      return <Badge color="danger">DOWN</Badge>;
    }
    return <Badge color="warning">?</Badge>;
  };

  const instanceInfo = route => {
    if (route) {
      return (
        <Table striped responsive>
          <tbody>
            {route.serviceInstances.map((instance, i) => (
              <tr key={`${instance.instanceInfo}-info`}>
                <td>
                  <a href={instance.uri} target="_blank" rel="noopener noreferrer">
                    {instance.uri}
                  </a>
                </td>
                <td>{badgeInfo(instance.healthService)}</td>
                <td>{metadata(instance.metadata)}</td>
              </tr>
            ))}
          </tbody>
        </Table>
      );
    }
  };

  const gatewayRoutes = () => {
    if (!isFetching) {
      dispatch(getGatewayRoutes());
    }
  };

  return (
    <div>
      <h2>Gateway</h2>
      <p>
        <Button onClick={gatewayRoutes} color={isFetching ? 'danger' : 'primary'} disabled={isFetching}>
          <FontAwesomeIcon icon="sync" />
          &nbsp;
          <Translate component="span" contentKey="health.refresh.button">
            Refresh
          </Translate>
        </Button>
      </p>

      <Table striped responsive>
        <thead>
          <tr key="header">
            <th>
              <Translate contentKey="gateway.routes.url">URL</Translate>
            </th>
            <th>
              <Translate contentKey="gateway.routes.service">Service</Translate>
            </th>
            <th>
              <Translate contentKey="gateway.routes.servers">Available servers</Translate>
            </th>
          </tr>
        </thead>
        <tbody>
          {routes.map((route, i) => (
            <tr key={`routes-${i}`}>
              <td>{route.path}</td>
              <td>{route.serviceId}</td>
              <td>{instanceInfo(route)}</td>
            </tr>
          ))}
        </tbody>
      </Table>
    </div>
  );
};

export default GatewayPage;
